/* Dollar-meter management panel. The UI has one source of truth: CPA's
 * completed Token callback plus the operator-maintained model rate card. */
(()=>{
  const root=document.documentElement;
  const syncTheme=()=>{let value='';try{const hostRoot=window.parent.document.documentElement;value=String(hostRoot.dataset.theme||hostRoot.dataset.colorScheme||hostRoot.className||'').toLowerCase()}catch{}root.dataset.cpaTheme=value.includes('dark')?'dark':'light'};
  syncTheme();
  try{new MutationObserver(syncTheme).observe(window.parent.document.documentElement,{attributes:true,attributeFilter:['class','data-theme','data-color-scheme']})}catch{}
})();

(()=>{
  const base='/v0/management/codex-carpool',authKey='cli-proxy-auth',legacyKey='managementKey',storageKey='codex-carpool:selected-key',securePrefix='enc::v1::',secureSalt='cli-proxy-api-webui::secure-storage';
  const state={summary:{keys:[],status:{},token_totals:{}},policies:[],models:[],rates:[],logs:[],selectedLogs:[],keyLogs:[],operationLogs:[],forbiddenLogs:[],selected:'',keyLogKeyID:'',rawKeys:[],editing:null,trend:{points:[]},trendError:'',keyTrends:{},dailyModelUsage:{models:[]},dailyModelUsageError:'',decisionPage:{page:1,page_size:10,total:0,total_pages:0},keyLogPage:{page:1,page_size:10,total:0,total_pages:0},operationPage:{page:1,page_size:10,total:0,total_pages:0},forbiddenPage:{page:1,page_size:10,total:0,total_pages:0},locale:''};
  const autoRefreshIntervalMS=5*60*1000;
  let pageRefreshPromise=null,lastPageRefreshAt=0,autoRefreshTimer=0,budgetBoundaryTimer=0;
  try{state.selected=String(localStorage.getItem(storageKey)||'')}catch{}
  const $=id=>document.getElementById(id);
  const value=v=>String(v??'').trim();
  const escapeHTML=v=>{const node=document.createElement('span');node.textContent=String(v??'');return node.innerHTML};
  const locale=()=>{let v='';try{const r=window.parent.document.documentElement;v=String(r.lang||r.dataset.locale||r.dataset.language||'')}catch{}return /^zh/i.test(v||navigator.language||'zh-CN')?'zh':'en'};
  const uiText=(zh,en)=>locale()==='zh'?zh:en;
  const number=v=>new Intl.NumberFormat(locale()==='zh'?'zh-CN':'en-US',{maximumFractionDigits:2}).format(Number(v)||0);
  const tokens=v=>{const n=Number(v)||0;if(n>=1000000)return number(n/1000000)+'M';if(n>=1000)return number(n/1000)+'K';return number(n)};
  const amountUSD=v=>{const n=Number(v);return Number.isFinite(n)?'$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4}):'—'};
  const budgetUSD=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?amountUSD(n):uiText('不限额','Unlimited')};
  const formatTime=v=>v?new Date(v).toLocaleString(locale()==='zh'?'zh-CN':'en-US',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
  const formatLogTime=v=>v?new Date(v).toLocaleString(locale()==='zh'?'zh-CN':'en-US',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}):'—';
  const suffix=key=>value(key?.key_suffix)?'••••'+value(key.key_suffix):uiText('尾号未知','Suffix unavailable');
  const keyFor=id=>state.summary.keys.find(key=>key.id===id);
  // CPAMP encrypts remembered management state with a lightweight,
  // origin-bound storage wrapper. Preserve plain JSON for older deployments.
  function decode(raw){if(!raw||!raw.startsWith(securePrefix))return raw||'';try{const encrypted=atob(raw.slice(securePrefix.length)),key=new TextEncoder().encode(secureSalt+'|'+location.host+'|'+navigator.userAgent),bytes=new Uint8Array(encrypted.length);for(let index=0;index<encrypted.length;index++)bytes[index]=encrypted.charCodeAt(index)^key[index%key.length];return new TextDecoder().decode(bytes)}catch{return ''}}
  function extractCPAKeys(payload){const lists=[payload?.['api-keys'],payload?.api_keys,payload?.apiKeys,payload?.keys,payload?.data].filter(Array.isArray);const result=[];for(const list of lists){for(const item of list){const key=typeof item==='string'?item:value(item?.api_key||item?.apiKey||item?.key||item?.token||item?.value);if(key)result.push(key)}}return Array.from(new Set(result))}
  function managementKey(){try{const decodeValue=raw=>{try{const parsed=JSON.parse(decode(raw)||'null');return typeof parsed==='string'?value(parsed):value(parsed?.state?.managementKey||parsed?.managementKey)}catch{return ''}};const first=decodeValue(localStorage.getItem(authKey)||'');if(first)return first;const second=decodeValue(localStorage.getItem(legacyKey)||'');if(second)return second}catch{}throw new Error(uiText('无法读取 CPAMP 已保存的登录状态，请刷新 CPAMP 页面后重试。','The saved CPAMP sign-in state could not be read. Refresh CPAMP and try again.'))}
  function showToast(message,ok=false){if(!message)return;let region=$('toast-region');if(!region){region=document.createElement('div');region.id='toast-region';region.setAttribute('aria-live','assertive');region.setAttribute('aria-atomic','true');(document.querySelector('.cc-panel')||document.body).append(region)}const toastKey=(ok?'ok:':'error:')+String(message),duplicate=Array.from(region.children).find(node=>node.dataset.toastKey===toastKey);if(duplicate)return;const item=document.createElement('div');item.dataset.toastKey=toastKey;item.setAttribute('role',ok?'status':'alert');item.className=ok?'ok':'error';item.textContent=message;region.append(item);item.onclick=()=>item.remove();setTimeout(()=>item.remove(),ok?3600:6500)}
  function errorMessage(error){if(error instanceof Error)return error.message;if(typeof error==='string')return error;try{return value(error?.error||error?.message||JSON.stringify(error))||uiText('操作失败。','Operation failed.')}catch{return uiText('操作失败。','Operation failed.')}}
  const dialogIDs=['policy-dialog','rate-card-dialog','log-detail-dialog','key-log-dialog','content-filter-dialog'];
  const activeDialog=()=>dialogIDs.map($).find(dialog=>dialog?.open);
  const closeDialog=id=>{const dialog=$(id);if(dialog)HTMLDialogElement.prototype.close.call(dialog)};
  function say(message,ok=false){const dialog=activeDialog(),textMessage=value(message);if(dialog){const node=dialog.querySelector('.dialog-message');if(node){node.hidden=!textMessage;node.textContent=textMessage;node.className='dialog-message'+(ok?' ok':'');return}}showToast(textMessage,ok)}
  async function call(root,path,options={}){const response=await fetch(root+path,Object.assign({},options,{headers:Object.assign({'Authorization':'Bearer '+managementKey(),'Accept-Language':locale()==='zh'?'zh-CN':'en-US'},options.headers||{})}));const payload=await response.json().catch(()=>({error:uiText('接口未返回 JSON','Response did not contain JSON')}));if(!response.ok)throw new Error(payload.error||uiText('请求失败 ','Request failed ')+response.status);return payload}
  const api=(path,opt)=>call(base,path,opt),host=(path,opt)=>call('/v0/management',path,opt);
  const panelCoreBridgeMarker=`const api=(path,opt)=>call(base,path,opt),host=(path,opt)=>call('/v0/management',path,opt);`;
  const panelCoreBridge=panelCoreBridgeMarker+`window.__ccPanelBridge?.attach?.({state,render,renderLogs,renderOperationalLogs,cpaLocale:locale,uiText,showToast,say,tokens});`;
  const cpaLocale=locale;
  const loadingTargets={full:['#stats','.meter-workbench','.logs'],key:['#key-detail-panel','#decision-log-view'],keyLog:['#key-log-dialog .key-log-form'],analysis:['#key-detail-panel'],decision:['#decision-log-view'],operation:['#operation-log-view'],forbidden:['#forbidden-log-view'],catalog:['.key-table-wrap']};
  function setLoading(targets,active,label=uiText('正在加载…','Loading…')){for(const selector of targets){const node=document.querySelector(selector);if(!node)continue;node.classList.toggle('cc-module-loading',active);node.setAttribute('aria-busy',active?'true':'false');if(active&&!node.querySelector(':scope>.cc-loading-overlay')){const overlay=document.createElement('div');overlay.className='cc-loading-overlay';overlay.innerHTML='<strong class="cc-loading-title">'+escapeHTML(label)+'</strong>';node.append(overlay)}if(!active)node.querySelector(':scope>.cc-loading-overlay')?.remove()}}
  const withLoading=async(targets,task,label)=>{setLoading(targets,true,label);try{return await task()}finally{setLoading(targets,false)}};

  function dollarBudgetText(window){const budget=Number(window?.budget_usd);return budget>0?amountUSD(window?.spent_usd)+' / '+amountUSD(budget):uiText('不限额','Unlimited')}
  function actualTotalText(key){const actual=key.actual_tokens||{};return actual.available?tokens(actual.total):'—'}
  function budgetRatio(spent,budget){const limit=Number(budget)||0;if(limit<=0)return null;return Math.min(100,Math.max(0,(Number(spent)||0)/limit*100))}
  function budgetPercentText(spent,budget){const ratio=budgetRatio(spent,budget);return ratio===null?uiText('不限','Unlimited'):ratio.toFixed(0)+'%'}
  function windowLabel(window,budget){const limit=Number(budget)||0;return limit>0?amountUSD(window?.spent_usd)+' / '+amountUSD(limit):amountUSD(window?.spent_usd)}
  function budgetRefreshText(window){return window?.refresh_at?formatTime(window.refresh_at):uiText('暂无','None')}
  function scheduleBudgetBoundaryRefresh(){if(budgetBoundaryTimer){clearTimeout(budgetBoundaryTimer);budgetBoundaryTimer=0}const now=Date.now(),boundaries=[];for(const key of state.summary.keys||[])for(const window of [key.dollar_spend?.five_hour,key.dollar_spend?.seven_day]){const at=Date.parse(window?.refresh_at||'');if(Number.isFinite(at)&&at>now)boundaries.push(at)}if(!boundaries.length)return;const delay=Math.max(50,Math.min(...boundaries)-now+150);budgetBoundaryTimer=window.setTimeout(()=>{budgetBoundaryTimer=0;refreshPageData({loading:false,resetLogs:false}).catch(error=>console.warn('quota management boundary refresh failed:',errorMessage(error)))},delay)}
  // CPA returns the whole day, so today's charts must use the local date and discard future buckets.
  function localDateISO(date=new Date()){const pad=part=>String(part).padStart(2,'0');return date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate())}
  function elapsedTrendPoints(points,now=Date.now()){return (Array.isArray(points)?points:[]).filter(point=>{const timestamp=Date.parse(point.start||point.at||'');return !Number.isFinite(timestamp)||timestamp<=now})}
  function sparkLine(points){const values=elapsedTrendPoints(points).slice(-12);if(!values.length||!values.some(point=>Number(point.units||0)>0))return '<span class="mini-trend-empty">'+uiText('今日暂无','None today')+'</span>';const width=132,height=34,pad=3,max=Math.max(1,...values.map(point=>Number(point.units||0))),x=index=>pad+(width-pad*2)*(values.length===1?0:index/(values.length-1)),y=value=>height-pad-(height-pad*2)*(Number(value)||0)/max,line=values.map((point,index)=>(index?'L':'M')+x(index).toFixed(1)+' '+y(point.units).toFixed(1)).join(' '),area='M'+pad+' '+(height-pad)+' '+values.map((point,index)=>'L'+x(index).toFixed(1)+' '+y(point.units).toFixed(1)).join(' ')+' L'+(width-pad)+' '+(height-pad)+' Z',dots=values.map((point,index)=>'<circle class="mini-dot" cx="'+x(index).toFixed(1)+'" cy="'+y(point.units).toFixed(1)+'" r="1.7"><title>'+escapeHTML((point.label||formatTime(point.start))+' · '+tokens(point.units)+' Token')+'</title></circle>').join(''),summary=uiText('今日截至当前小时，共 ','Today through the current hour, ')+tokens(values.reduce((sum,point)=>sum+Number(point.units||0),0))+' Token';return '<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+escapeHTML(summary)+'"><title>'+escapeHTML(summary)+'</title><path class="mini-area" d="'+area+'"></path><path class="mini-line" d="'+line+'"></path>'+dots+'</svg>'}
  function todayRange(){const now=new Date(),iso=localDateISO(now);return {from:iso,to:iso,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai'}}
  function rateFor(model){return state.rates.find(rate=>value(rate.model)===value(model))||null}
  function costPartsForLog(log){const stored=[log.input_cost_micros,log.cached_cost_micros,log.output_cost_micros].map(part=>(Number(part)||0)/1000000);if(stored.some(Boolean))return {input:stored[0],cached:stored[1],output:stored[2]};const rate=rateFor(log.model),input=Number(log.input_tokens)||0,cached=Number(log.cached_tokens)||0,output=Number(log.output_tokens)||0;if(rate){return {input:input*(Number(rate.input_usd_per_million)||0)/1000000,cached:cached*(Number(rate.cached_usd_per_million)||0)/1000000,output:output*(Number(rate.output_usd_per_million)||0)/1000000}}const total=(Number(log.cost_micros)||0)/1000000,units=input+cached+output||1;return {input:total*input/units,cached:total*cached/units,output:total*output/units}}
  function selectedLogStats(){const trend=state.trend||{},stats={inputTokens:Number(trend.input_tokens)||0,cachedTokens:Number(trend.cached_tokens)||0,outputTokens:Number(trend.output_tokens)||0,inputCost:(Number(trend.input_cost_micros)||0)/1000000,cachedCost:(Number(trend.cached_cost_micros)||0)/1000000,outputCost:(Number(trend.output_cost_micros)||0)/1000000,totalCost:(Number(trend.cost_micros)||0)/1000000,byModel:new Map};for(const item of trend.models||[]){stats.byModel.set(value(item.model)||'—',(Number(item.cost_micros)||0)/1000000)}return stats}
  function hbar(label,valueText,ratio,color){return '<div class="hmetric" style="--bar-color:'+color+'"><span title="'+escapeHTML(label)+'">'+escapeHTML(label)+'</span><div class="mini-track"><i style="width:'+Math.max(0,Math.min(100,ratio)).toFixed(1)+'%"></i></div><strong>'+valueText+'</strong></div>'}

  function renderSyncStatus(){const status=state.summary.status||{};const warning=status.persistence_degraded?uiText('账本持久化异常，已添加 Key 请求暂停','Ledger persistence is degraded; requests from added Keys are paused'):state.modelSyncError;const syncAt=state.models.map(m=>m.synced_at).filter(Boolean).sort().pop();$('sync-state').textContent=warning||uiText('已连接用量管理','Connected to usage management');$('sync-state').parentElement.classList.toggle('warn',Boolean(warning));$('sync-time').textContent=syncAt?uiText('模型目录：','Models: ')+formatTime(syncAt):''}
  function renderStats(){const totals=state.summary.token_totals||{},available=Boolean(totals.available),items=[[uiText('输入 Token','Input Tokens'),available?tokens(totals.input):'—','trend'],[uiText('缓存 Token','Cached Tokens'),available?tokens(totals.cached):'—','layers'],[uiText('输出 Token','Output Tokens'),available?tokens(totals.output):'—','split'],[uiText('已添加 Key','Added Keys'),number((state.summary.keys||[]).length),'key']];$('stats').innerHTML=items.map(([name,count,icon])=>'<article class="stat-card stat-card--'+icon+'"><span class="stat-icon"><svg class="cc-icon"><use href="#cc-icon-'+icon+'"></use></svg></span><div><div class="stat-name">'+name+'</div><div class="stat-value">'+count+'</div></div></article>').join('')}
  function renderKeys(){
    const all=state.summary.keys||[],filter=value($('search')?.value).toLowerCase(),status=value($('key-status-filter')?.value),keys=all.filter(key=>(value(key.name)+' '+value(key.key_suffix)).toLowerCase().includes(filter)).filter(key=>status==='enabled'?key.enabled:status==='disabled'?!key.enabled:true);
    if(!all.some(key=>key.id===state.selected)){state.selected=all[0]?.id||'';try{localStorage.setItem(storageKey,state.selected)}catch{}}
    if($('key-list-count'))$('key-list-count').textContent=number(all.length);
    $('keys').innerHTML=keys.length?keys.map(key=>{
      const five=key.dollar_spend?.five_hour||{},week=key.dollar_spend?.seven_day||{},status=key.enabled?uiText('额度限制','Budget enforced'):uiText('仅统计','Track only');
      const fiveRatio=budgetRatio(five.spent_usd,key.five_hour_budget_usd),weekRatio=budgetRatio(week.spent_usd,key.seven_day_budget_usd),actual=key.actual_tokens||{},trend=state.keyTrends[key.id];
      return '<tr data-key-id="'+escapeHTML(key.id)+'"><td><strong>'+escapeHTML(key.name||'—')+'</strong><small>'+escapeHTML(suffix(key))+'</small></td><td><div class="budget-cell"><div class="budget-cell-top"><strong>'+budgetPercentText(five.spent_usd,key.five_hour_budget_usd)+'</strong><em>'+windowLabel(five,key.five_hour_budget_usd)+'</em></div><div class="mini-track"><i style="width:'+(fiveRatio===null?0:fiveRatio).toFixed(1)+'%"></i></div></div></td><td><div class="budget-cell"><div class="budget-cell-top"><strong>'+budgetPercentText(week.spent_usd,key.seven_day_budget_usd)+'</strong><em>'+windowLabel(week,key.seven_day_budget_usd)+'</em></div><div class="mini-track"><i style="width:'+(weekRatio===null?0:weekRatio).toFixed(1)+'%"></i></div></div></td><td><strong>'+actualTotalText(key)+'</strong><small>'+(actual.available?tokens(actual.input)+' / '+tokens(actual.cached)+' / '+tokens(actual.output):'—')+'</small></td><td><div class="mini-trend" aria-label="'+uiText('今日按小时趋势','Today hourly trend')+'">'+sparkLine(trend)+'</div></td><td><span class="pill '+(key.enabled?'':'off')+'">'+status+'</span></td><td class="key-action"><div class="key-row-actions"><button type="button" class="analysis-open" data-analysis-key="'+escapeHTML(key.id)+'"><svg class="cc-icon"><use href="#cc-icon-panel"></use></svg>'+uiText('管理','Manage')+'</button><button type="button" class="key-log-open" data-key-log="'+escapeHTML(key.id)+'"><svg class="cc-icon"><use href="#cc-icon-list"></use></svg>'+uiText('日志','Logs')+'</button></div></td></tr>';
    }).join(''):'<tr><td colspan="7" class="empty">'+uiText('暂无已添加 Key，请新增 Key。','No added Keys yet. Add a Key to begin.')+'</td></tr>';
    document.querySelectorAll('[data-analysis-key]').forEach(button=>button.onclick=event=>{event.stopPropagation();selectKey(button.dataset.analysisKey);openKeyDetail();loadSelected().catch(error=>say(error.message))});
    document.querySelectorAll('[data-key-log]').forEach(button=>button.onclick=event=>{event.stopPropagation();openKeyLogs(button.dataset.keyLog)});
  }
  function renderDailyModelRanking(){
    const node=$('daily-model-ranking'),totalNode=$('daily-model-total'),countNode=$('daily-model-count');if(!node||!totalNode||!countNode)return;
    const snapshot=state.dailyModelUsage||{},items=snapshot.models||[],modelCount=items.length,maxCost=Math.max(0,...items.map(item=>Number(item.cost_micros)||0)),maxTokens=Math.max(1,...items.map(item=>Number(item.total_tokens)||0));
    countNode.textContent=number(modelCount)+uiText(' 个',' models');countNode.title=uiText('今日有用量的模型数量：','Models used today: ')+number(modelCount);countNode.setAttribute('aria-label',countNode.title);
    if(state.dailyModelUsageError){node.innerHTML='<div class="daily-model-empty">'+escapeHTML(state.dailyModelUsageError)+'</div>';totalNode.innerHTML='';return}
    node.innerHTML=items.length?items.map((item,index)=>{const cost=(Number(item.cost_micros)||0)/1000000,tokenCount=Number(item.total_tokens)||0,ratio=maxCost>0?(Number(item.cost_micros)||0)/maxCost*100:tokenCount/maxTokens*100;return '<article class="daily-model-item" style="--daily-model-ratio:'+Math.max(0,Math.min(100,ratio)).toFixed(2)+'%"><span class="daily-model-rank">'+(index+1)+'</span><div class="daily-model-name"><strong title="'+escapeHTML(item.model||'—')+'">'+escapeHTML(item.model||'—')+'</strong><small>'+tokens(tokenCount)+' Token · '+number(item.request_count)+uiText(' 次请求',' requests')+'</small></div><b>'+amountUSD(cost)+'</b></article>'}).join(''):'<div class="daily-model-empty">'+uiText('今日暂无模型用量','No model usage today')+'</div>';
    totalNode.innerHTML='<span>'+uiText('今日合计','Today total')+'</span><strong>'+tokens(snapshot.total_tokens)+' Token</strong><b>'+amountUSD((Number(snapshot.cost_micros)||0)/1000000)+'</b>';
  }
  function selectKey(id){state.selected=value(id);try{localStorage.setItem(storageKey,state.selected)}catch{}}
  function openKeyDetail(){renderDetail();renderAnalysis();document.querySelector('.cc-panel')?.classList.add('drawer-open');$('key-detail-panel')?.setAttribute('aria-hidden','false');const body=document.querySelector('#key-detail-panel .drawer-body');if(body)body.scrollTop=0}
  function closeKeyDetail(){document.querySelector('.cc-panel')?.classList.remove('drawer-open');$('key-detail-panel')?.setAttribute('aria-hidden','true')}
  function renderDetail(){const key=keyFor(state.selected),detail=$('detail');if(!key){$('analysis-name').textContent=uiText('请选择 Key','Select a Key');$('analysis-suffix').textContent='—';$('analysis-status').textContent='—';$('analysis-status').className='pill off';detail.innerHTML='<div class="empty">'+uiText('选择一个 Key 查看用量。','Select a Key to view usage.')+'</div>';$('token-breakdown').innerHTML='';$('token-progress').innerHTML='';return}const five=key.dollar_spend?.five_hour||{},week=key.dollar_spend?.seven_day||{},budgetRow=(label,window,budget)=>{const ratio=budgetRatio(window.spent_usd,budget),width=ratio===null?0:ratio;return '<article class="budget-row"><div class="budget-row-main"><span>'+label+'</span><strong>'+budgetPercentText(window.spent_usd,budget)+'</strong><small>'+dollarBudgetText({budget_usd:Number(budget)||0,spent_usd:Number(window.spent_usd)||0})+'</small></div><div class="budget-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+Math.round(width)+'"><i style="width:'+width.toFixed(2)+'%"></i></div><div class="budget-row-foot"><small class="budget-percent '+(ratio===null?'unlimited':'')+'">'+(ratio===null?uiText('不限额','Unlimited'):uiText('剩余 ','Remaining ')+budgetUSD(window.remaining_usd))+'</small><small class="budget-refresh"><span>'+uiText('下次刷新','Next refresh')+'</span><strong>'+escapeHTML(budgetRefreshText(window))+'</strong></small></div></article>'};$('analysis-name').textContent=key.name||'—';$('analysis-suffix').textContent=suffix(key);$('analysis-status').textContent=key.enabled?uiText('额度限制','Budget enforced'):uiText('仅统计','Track only');$('analysis-status').className='pill '+(key.enabled?'':'off');detail.innerHTML=budgetRow(uiText('5 小时','5-hour'),five,key.five_hour_budget_usd)+budgetRow(uiText('7 天','7-day'),week,key.seven_day_budget_usd)}
  function renderRangeTokenBreakdown(stats){const items=[[uiText('输入 Token','Input Tokens'),stats.inputTokens,'input','#3b82f6'],[uiText('缓存 Token','Cached Tokens'),stats.cachedTokens,'cached','var(--cc-primary)'],[uiText('输出 Token','Output Tokens'),stats.outputTokens,'output','var(--cc-warn)']],total=items.reduce((sum,item)=>sum+item[1],0);$('token-breakdown').innerHTML=state.trendError?'<div class="empty">'+escapeHTML(state.trendError)+'</div>':items.map(item=>hbar(item[0],tokens(item[1]),total?item[1]/total*100:0,item[3])).join('');$('token-progress').innerHTML=!state.trendError&&total?items.filter(item=>item[1]>0).map(item=>'<i class="'+item[2]+'" style="flex:'+item[1]+'" title="'+escapeHTML(item[0])+' · '+tokens(item[1])+'"></i>').join(''):''}
  function renderAnalysis(){const trend=state.trend||{points:[]},points=trend.points||[],key=keyFor(state.selected),stats=selectedLogStats(),total=Number(trend.total_tokens)||points.reduce((sum,p)=>sum+Number(p.units||0),0),requestCount=trend.request_count||points.reduce((sum,p)=>sum+Number(p.request_count||0),0),display=state.trendError?'—':tokens(total),modelCount=(trend.models||[]).length;$('analysis-metrics').innerHTML='<div><span>'+uiText('区间 Token','Range Tokens')+'</span><strong>'+display+'</strong></div><div><span>'+uiText('请求次数','Requests')+'</span><strong>'+(state.trendError?'—':number(requestCount))+'</strong></div><div><span>'+uiText('区间消耗','Range spend')+'</span><strong>'+(state.trendError?'—':amountUSD(stats.totalCost))+'</strong></div><div><span>'+uiText('使用模型','Models used')+'</span><strong>'+(state.trendError?'—':number(modelCount))+'</strong></div>';renderLineChart(points,total);renderCostDonut(stats);renderModelRanking(stats);renderRangeTokenBreakdown(stats);renderHeatmap(points);renderAnalysisLogs();renderRisks(key,stats);$('trend-from').textContent=state.trendError?state.trendError:(trend.from?formatTime(trend.from):uiText('暂无已结算历史','No settled history'));$('trend-total').textContent=state.trendError?'—':tokens(total)+' Token'}
  function chartPointSummary(point){return (point.label||formatTime(point.start))+' · '+tokens(point.units)+' Token · '+uiText('请求 ','Requests ')+number(point.request_count)}
  function chartTooltipHTML(point){return '<strong>'+escapeHTML(point.label||formatTime(point.start))+'</strong><span><em>Token</em><b>'+tokens(point.units)+'</b></span><span><em>'+uiText('请求次数','Requests')+'</em><b>'+number(point.request_count)+'</b></span><span><em>'+uiText('输入 / 缓存 / 输出','Input / cached / output')+'</em><b>'+tokens(point.input_tokens)+' / '+tokens(point.cached_tokens)+' / '+tokens(point.output_tokens)+'</b></span><span><em>'+uiText('消耗','Spend')+'</em><b>'+amountUSD((Number(point.cost_micros)||0)/1000000)+'</b></span>'}
  function wireLineChartTooltip(node,values){const tooltip=node.querySelector('.chart-tooltip');if(!tooltip)return;const hide=()=>{tooltip.hidden=true};const show=(target,event)=>{const point=values[Number(target.dataset.chartPoint)];if(!point)return;tooltip.innerHTML=chartTooltipHTML(point);tooltip.hidden=false;const bounds=node.getBoundingClientRect(),anchor=event&&Number.isFinite(event.clientX)?{x:event.clientX-bounds.left,y:event.clientY-bounds.top}:(()=>{const rect=target.getBoundingClientRect();return {x:rect.left+rect.width/2-bounds.left,y:rect.top+rect.height/2-bounds.top}})(),left=Math.max(8,Math.min(bounds.width-tooltip.offsetWidth-8,anchor.x-tooltip.offsetWidth/2));let top=anchor.y-tooltip.offsetHeight-12;if(top<8)top=anchor.y+12;tooltip.style.left=left+'px';tooltip.style.top=Math.min(bounds.height-tooltip.offsetHeight-8,top)+'px'};node.querySelectorAll('[data-chart-point]').forEach(target=>{target.onpointerenter=event=>show(target,event);target.onpointermove=event=>show(target,event);target.onpointerleave=hide;target.onfocus=event=>show(target,event);target.onblur=hide})}
  function renderLineChart(points,total){const node=$('chart');if(!node)return;if(state.trendError){node.innerHTML='<span class="chart-empty">'+escapeHTML(state.trendError)+'</span>';return}const values=elapsedTrendPoints(points).slice(-24);if(!values.length){node.innerHTML='<span class="chart-empty">'+uiText('暂无已结算历史','No settled history')+'</span>';return}const width=420,height=160,pad=18,max=Math.max(1,...values.map(point=>Number(point.units||0))),x=index=>pad+(width-pad*2)*(values.length===1?0:index/(values.length-1)),y=value=>height-pad-(height-pad*2)*(Number(value)||0)/max,line=values.map((point,index)=>(index?'L':'M')+x(index).toFixed(1)+' '+y(point.units).toFixed(1)).join(' '),area='M'+pad+' '+(height-pad)+' '+values.map((point,index)=>'L'+x(index).toFixed(1)+' '+y(point.units).toFixed(1)).join(' ')+' L'+(width-pad)+' '+(height-pad)+' Z',dots=values.map((point,index)=>'<circle class="chart-dot" cx="'+x(index).toFixed(1)+'" cy="'+y(point.units).toFixed(1)+'" r="3"></circle><circle class="chart-hit" data-chart-point="'+index+'" tabindex="0" cx="'+x(index).toFixed(1)+'" cy="'+y(point.units).toFixed(1)+'" r="10" aria-label="'+escapeHTML(chartPointSummary(point))+'"></circle>').join('');node.innerHTML='<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="'+escapeHTML(uiText('Token 趋势折线图','Token trend line chart'))+'"><path class="chart-grid" d="M'+pad+' '+(height-pad)+'H'+(width-pad)+'M'+pad+' '+(height/2).toFixed(1)+'H'+(width-pad)+'M'+pad+' '+pad+'H'+(width-pad)+'"/><path class="chart-area" d="'+area+'"/><path class="chart-line" d="'+line+'"/>'+dots+'<text class="chart-label" x="'+pad+'" y="'+(height-3)+'">'+escapeHTML(values[0]?.label||formatTime(values[0]?.start))+'</text><text class="chart-label" x="'+(width-pad)+'" y="'+(height-3)+'" text-anchor="end">'+escapeHTML(values[values.length-1]?.label||formatTime(values[values.length-1]?.start))+'</text></svg><div class="chart-tooltip" role="tooltip" hidden></div>';wireLineChartTooltip(node,values)}
  function renderCostDonut(stats){const node=$('cost-donut');if(!node)return;const total=stats.inputCost+stats.cachedCost+stats.outputCost||stats.totalCost||0,input=total?stats.inputCost/total*100:0,output=input+(total?stats.outputCost/total*100:0),cached=output+(total?stats.cachedCost/total*100:0);node.innerHTML='<div class="cost-donut" style="--input:'+input.toFixed(2)+'%;--output:'+output.toFixed(2)+'%;--cached:'+cached.toFixed(2)+'%" data-total="'+amountUSD(total)+'"></div><div class="cost-legend"><span><em><i></i>'+uiText('输入成本','Input cost')+'</em><strong>'+amountUSD(stats.inputCost)+'</strong></span><span><em><i></i>'+uiText('输出成本','Output cost')+'</em><strong>'+amountUSD(stats.outputCost)+'</strong></span><span><em><i></i>'+uiText('缓存成本','Cached cost')+'</em><strong>'+amountUSD(stats.cachedCost)+'</strong></span><span><em><i></i>'+uiText('区间总额','Range total')+'</em><strong>'+amountUSD(total)+'</strong></span></div>'}
  function renderModelRanking(stats){const node=$('model-ranking');if(!node)return;const items=Array.from(stats.byModel.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...items.map(item=>item[1]));node.innerHTML=items.length?items.map((item,index)=>hbar(item[0],amountUSD(item[1]),item[1]/max*100,index===0?'var(--cc-primary)':index===1?'#3b82f6':'var(--cc-warn)')).join(''):'<div class="empty">'+uiText('暂无模型消耗','No model spend yet')+'</div>'}
  function renderHeatmap(points){const node=$('usage-heatmap');if(!node)return;const values=elapsedTrendPoints(points).slice(-21);if(!values.length||!values.some(point=>Number(point.units||0)>0)){node.innerHTML='<div class="empty">'+uiText('暂无活跃数据','No activity data')+'</div>';return}const max=Math.max(1,...values.map(point=>Number(point.units||0)));node.innerHTML=values.map(point=>'<i style="--heat:'+Math.max(8,Math.round(Number(point.units||0)/max*92))+'%" title="'+escapeHTML(point.label||formatTime(point.start))+' · '+tokens(point.units)+'"></i>').join('')}
  function renderAnalysisLogs(){const node=$('analysis-log-snapshot');if(!node)return;const logs=(state.selectedLogs||[]).slice(0,4);node.innerHTML=logs.length?logs.map(log=>'<div class="analysis-log-item"><span>'+escapeHTML(formatTime(log.requested_at))+'</span><div><strong>'+escapeHTML(decisionText(log))+' · '+escapeHTML(log.model||'—')+'</strong><small>'+tokens(log.input_tokens)+' / '+tokens(log.cached_tokens)+' / '+tokens(log.output_tokens)+'</small></div><b>'+amountUSD((Number(log.cost_micros)||0)/1000000)+'</b></div>').join(''):'<div class="empty">'+uiText('暂无日志摘要','No log summary')+'</div>'}
  function renderRisks(key,stats){const node=$('risk-list');if(!node)return;const missingRates=(state.models||[]).filter(model=>!rateFor(model.id)).length,risks=[];if(missingRates>0)risks.push(['warn',uiText('模型费率缺失','Missing model rates'),uiText('有 ','')+missingRates+uiText(' 个 CPA 模型未配置费率。',' CPA models have no configured rate.'),'rates']);const five=key?.dollar_spend?.five_hour||{},week=key?.dollar_spend?.seven_day||{},fiveRatio=budgetRatio(five.spent_usd,key?.five_hour_budget_usd),weekRatio=budgetRatio(week.spent_usd,key?.seven_day_budget_usd);if(fiveRatio!==null&&fiveRatio>=80)risks.push(['warn',uiText('5 小时预算临近','5-hour budget is close'),fiveRatio.toFixed(0)+'%']);if(weekRatio!==null&&weekRatio>=80)risks.push(['warn',uiText('7 天预算临近','7-day budget is close'),weekRatio.toFixed(0)+'%']);if(!risks.length)risks.push(['ok',uiText('当前无明显风险','No obvious risk'),uiText('费率、预算和日志状态正常。','Rates, budgets, and logs look normal.')]);node.innerHTML=risks.map(item=>'<div class="risk-item '+item[0]+'"><svg class="cc-icon"><use href="#cc-icon-'+(item[0]==='ok'?'check':'alert')+'"></use></svg><span><strong>'+escapeHTML(item[1])+'</strong><small>'+escapeHTML(item[2])+'</small></span>'+(item[3]?'<button type="button" data-risk-action="'+item[3]+'">'+uiText('查看','View')+'</button>':'')+'</div>').join('')}
  function decisionText(log){return log.decision==='completed'?uiText('完成','Completed'):log.decision==='blocked'?uiText('拦截','Blocked'):log.decision==='failed'?uiText('失败','Failed'):log.decision==='ignored'?uiText('忽略','Ignored'):uiText('已记录','Recorded')}
  function previewText(input,max=96){const text=value(input);return !text?'—':text.length>max?text.slice(0,max)+'…':text}
  function renderLogs(){const logs=state.logs||[];$('logs').innerHTML=logs.length?logs.map((log,index)=>'<tr><td>'+escapeHTML(formatLogTime(log.requested_at))+'</td><td>'+escapeHTML(keyFor(log.key_id)?.name||'—')+'</td><td>'+escapeHTML(log.model||'—')+'</td><td class="log-request-preview"><span>'+escapeHTML(previewText(log.request_content))+'</span></td><td><span class="decision '+(log.decision==='completed'?'allow':(log.decision==='blocked'||log.decision==='failed'?'reject':'throttle'))+'">'+escapeHTML(decisionText(log))+'</span></td><td>'+tokens(log.input_tokens)+'</td><td>'+tokens(log.cached_tokens)+'</td><td>'+tokens(log.output_tokens)+'</td><td>'+amountUSD((Number(log.cost_micros)||0)/1000000)+'</td><td>'+escapeHTML(log.status_code||'—')+'</td><td>'+escapeHTML(log.auth_id||'—')+'</td><td title="'+escapeHTML(log.reason||'')+'">'+escapeHTML(log.reason||'—')+'</td><td class="log-action"><button type="button" class="row-action log-detail-open" data-log-index="'+index+'"><svg class="cc-icon"><use href="#cc-icon-eye"></use></svg>'+uiText('查看','View')+'</button></td></tr>').join(''):'<tr><td colspan="13" class="empty">'+uiText('暂无使用日志。','No usage logs yet.')+'</td></tr>';const page=state.decisionPage;$('decision-page-info').textContent=uiText('共 ','Total ')+number(page.total||logs.length)+uiText(' 条','');$('decision-page-number').textContent=uiText('第 ','Page ')+number(page.page||1)+' / '+number(page.total_pages||1)+uiText(' 页','');$('decision-prev').disabled=(page.page||1)<=1;$('decision-next').disabled=(page.page||1)>=(page.total_pages||1)}
  // The standalone Key log dialog owns its paging state so it never changes
  // the global log table or the Key currently open in the analysis drawer.
  function renderKeyLogs(){const logs=state.keyLogs||[],key=keyFor(state.keyLogKeyID),page=state.keyLogPage||{};$('key-log-subtitle').textContent=key?(key.name||'—')+' · '+suffix(key):uiText('仅显示当前 Key 的请求记录','Only requests for the current Key');$('key-logs').innerHTML=logs.length?logs.map((log,index)=>'<tr><td>'+escapeHTML(formatLogTime(log.requested_at))+'</td><td title="'+escapeHTML(log.model||'')+'">'+escapeHTML(log.model||'—')+'</td><td class="log-request-preview"><span>'+escapeHTML(previewText(log.request_content,120))+'</span></td><td><span class="decision '+(log.decision==='completed'?'allow':(log.decision==='blocked'||log.decision==='failed'?'reject':'throttle'))+'">'+escapeHTML(decisionText(log))+'</span></td><td>'+tokens(log.input_tokens)+' / '+tokens(log.cached_tokens)+' / '+tokens(log.output_tokens)+'</td><td>'+amountUSD((Number(log.cost_micros)||0)/1000000)+'</td><td>'+escapeHTML(log.status_code||'—')+'</td><td class="log-action"><button type="button" class="row-action key-log-detail" data-key-log-index="'+index+'"><svg class="cc-icon"><use href="#cc-icon-eye"></use></svg>'+uiText('查看','View')+'</button></td></tr>').join(''):'<tr><td colspan="8" class="empty">'+uiText('该 Key 暂无请求日志。','No request logs for this Key.')+'</td></tr>';$('key-log-page-info').textContent=uiText('共 ','Total ')+number(page.total||logs.length)+uiText(' 条','');$('key-log-page-number').textContent=uiText('第 ','Page ')+number(page.page||1)+' / '+number(page.total_pages||1)+uiText(' 页','');$('key-log-prev').disabled=(page.page||1)<=1;$('key-log-next').disabled=(page.page||1)>=(page.total_pages||1)}
  function renderOperationalLogs(){const logs=state.operationLogs||[];$('operation-logs').innerHTML=logs.length?logs.map(log=>'<tr><td>'+escapeHTML(formatLogTime(log.occurred_at))+'</td><td>'+escapeHTML(value(log.level).toUpperCase())+'</td><td>'+escapeHTML(log.event||'—')+'</td><td>'+escapeHTML(log.auth_id||'—')+'</td><td>'+escapeHTML(log.message||'—')+'</td></tr>').join(''):'<tr><td colspan="5" class="empty">'+uiText('暂无运行日志。','No runtime logs yet.')+'</td></tr>';const page=state.operationPage;$('operation-page-info').textContent=uiText('共 ','Total ')+number(page.total||logs.length)+uiText(' 条','');$('operation-page-number').textContent=uiText('第 ','Page ')+number(page.page||1)+' / '+number(page.total_pages||1)+uiText(' 页','');$('operation-prev').disabled=(page.page||1)<=1;$('operation-next').disabled=(page.page||1)>=(page.total_pages||1)}
  function renderForbiddenLogs(){const logs=state.forbiddenLogs||[];$('forbidden-logs').innerHTML=logs.length?logs.map((log,index)=>'<tr><td>'+escapeHTML(formatLogTime(log.requested_at))+'</td><td>'+escapeHTML(keyFor(log.key_id)?.name||'—')+'</td><td>'+escapeHTML(log.model||'—')+'</td><td class="log-request-preview"><span>'+escapeHTML(previewText(log.request_content))+'</span></td><td>'+escapeHTML(log.matched_term||'—')+'</td><td>'+escapeHTML(log.matched_category||'—')+'</td><td>'+escapeHTML(log.auth_id||'—')+'</td><td class="log-action"><button type="button" class="row-action forbidden-log-detail" data-log-index="'+index+'"><svg class="cc-icon"><use href="#cc-icon-eye"></use></svg>'+uiText('查看','View')+'</button></td></tr>').join(''):'<tr><td colspan="8" class="empty">'+uiText('暂无内容拦截日志。','No content-blocking logs yet.')+'</td></tr>';const page=state.forbiddenPage||{};$('forbidden-page-info').textContent=uiText('共 ','Total ')+number(page.total||logs.length)+uiText(' 条','');$('forbidden-page-number').textContent=uiText('第 ','Page ')+number(page.page||1)+' / '+number(page.total_pages||1)+uiText(' 页','');$('forbidden-prev').disabled=(page.page||1)<=1;$('forbidden-next').disabled=(page.page||1)>=(page.total_pages||1)}
  function render(){renderStats();renderSyncStatus();renderKeys();renderDailyModelRanking();renderDetail();renderAnalysis();renderLogs();renderKeyLogs();renderOperationalLogs();renderForbiddenLogs();window.__ccPanelBridge?.afterRender?.()}
  window.__ccRenderUsageLineChart=()=>renderAnalysis();

  async function loadSummary(){const payload=await api('/summary');state.summary=payload;state.policies=payload.keys||[];scheduleBudgetBoundaryRefresh();render()}
  async function loadModels(){const payload=await api('/models');state.models=(payload.models||[]).filter(model=>model.available!==false);return state.models}
  async function loadRates(){const payload=await api('/rates');state.rates=payload.rates||[];return state.rates}
  // Read downstream API Keys from CPA's canonical configuration endpoint.
  // CPA Home can claim the similarly named /api-keys route for its wallet UI,
  // so the panel must not call that ambiguous route.
  async function loadKeys(){const payload=await host('/config');state.rawKeys=extractCPAKeys(payload);return state.rawKeys}
  async function loadSelected(){await Promise.all([loadTrend(),loadSelectedLogs()]);render()}
  async function loadTrend(){if(!state.selected){state.trend={points:[]};state.trendError='';return}const from=$('analysis-from').value,to=$('analysis-to').value,params=new URLSearchParams({key_id:state.selected,from,to,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai',granularity:$('analysis-granularity').value||'hour'});try{state.trend=await api('/analysis?'+params);state.trendError='';if($('analysis-preset')?.value==='today'&&($('analysis-granularity')?.value||'hour')==='hour')state.keyTrends[state.selected]=state.trend.points||[]}catch(error){state.trend={points:[]};state.trendError=errorMessage(error)}}
  // Public list metadata always covers every Key and never follows drawer selection.
  // The compact Key list owns only today's trend; detailed model data remains in the analysis and log views.
  async function loadKeySparklines(){const range=todayRange(),keys=state.summary.keys||[],current=new Set(keys.map(key=>key.id));for(const keyID of Object.keys(state.keyTrends))if(!current.has(keyID))delete state.keyTrends[keyID];await Promise.allSettled(keys.map(key=>{state.keyTrends[key.id]=[];const trendParams=new URLSearchParams({key_id:key.id,from:range.from,to:range.to,timezone:range.timezone,granularity:'hour'});return api('/analysis?'+trendParams).then(payload=>{state.keyTrends[key.id]=payload.points||[]})}));renderKeys()}
  // The public ranking is an all-Key daily rollup and never follows drawer selection.
  async function loadDailyModelRanking(){const range=todayRange(),params=new URLSearchParams(range);try{state.dailyModelUsage=await api('/model-ranking?'+params);state.dailyModelUsageError=''}catch(error){state.dailyModelUsage={models:[]};state.dailyModelUsageError=errorMessage(error)}renderDailyModelRanking()}
  async function loadSelectedLogs(){if(!state.selected){state.selectedLogs=[];return}const params=new URLSearchParams({key_id:state.selected,page:'1',page_size:'4'}),payload=await api('/logs?'+params);state.selectedLogs=payload.logs||[]}
  async function loadDecisionLogs(reset){if(reset)state.decisionPage.page=1;const params=new URLSearchParams({page:String(state.decisionPage.page||1),page_size:String(state.decisionPage.page_size||10)}),query=value($('decision-search').value),decision=value($('decision-filter').value);if(query)params.set('query',query);if(decision)params.set('decision',decision);const payload=await api('/logs?'+params);state.logs=payload.logs||[];state.decisionPage=payload;renderLogs()}
  // Convert the operator's local range to stable UTC query boundaries; the
  // backend combines them with the current Key and keyword in one SQL page.
  function keyLogFilterParams(){const params={},fromValue=value($('key-log-from').value),toValue=value($('key-log-to').value),query=value($('key-log-search').value),from=fromValue?new Date(fromValue):null,to=toValue?new Date(toValue):null;if(from&&Number.isNaN(from.getTime()))throw new Error(uiText('开始时间无效。','Start time is invalid.'));if(to&&Number.isNaN(to.getTime()))throw new Error(uiText('结束时间无效。','End time is invalid.'));if(from&&to&&from>to)throw new Error(uiText('结束时间不能早于开始时间。','End time must not be before start time.'));if(from)params.from=from.toISOString();if(to)params.to=to.toISOString();if(query)params.query=query;return params}
  async function loadKeyLogs(reset=false){if(!state.keyLogKeyID){state.keyLogs=[];state.keyLogPage={page:1,page_size:10,total:0,total_pages:0};renderKeyLogs();return}if(reset)state.keyLogPage.page=1;const params=new URLSearchParams({key_id:state.keyLogKeyID,page:String(state.keyLogPage.page||1),page_size:'10',...keyLogFilterParams()}),payload=await api('/logs?'+params);state.keyLogs=payload.logs||[];state.keyLogPage=payload;renderKeyLogs()}
  async function loadOperationalLogs(reset=false){if(reset)state.operationPage.page=1;const params=new URLSearchParams({page:String(state.operationPage.page||1),page_size:'10',query:value($('operation-search').value)});const payload=await api('/operation-logs?'+params);state.operationLogs=payload.logs||[];state.operationPage=payload;renderOperationalLogs()}
  async function loadForbiddenLogs(reset=false){if(reset)state.forbiddenPage.page=1;const params=new URLSearchParams({page:String(state.forbiddenPage.page||1),page_size:'10',query:value($('forbidden-search').value)});const payload=await api('/forbidden-logs?'+params);state.forbiddenLogs=payload.logs||[];state.forbiddenPage=payload;renderForbiddenLogs()}
  async function refreshPageData({loading=false,resetLogs=false}={}){if(pageRefreshPromise)return pageRefreshPromise;const task=async()=>{await Promise.all([loadSummary(),loadModels(),loadRates()]);await Promise.all([loadKeySparklines(),loadDailyModelRanking(),loadDecisionLogs(resetLogs),loadSelected()]);const activeTab=document.querySelector('.logs')?.dataset.logTab;if(activeTab==='operation')await loadOperationalLogs(resetLogs);if(activeTab==='forbidden')await loadForbiddenLogs(resetLogs);lastPageRefreshAt=Date.now();render()};pageRefreshPromise=(loading?withLoading(loadingTargets.full,task):task()).finally(()=>{pageRefreshPromise=null});return pageRefreshPromise}
  function startAutoRefresh(){if(autoRefreshTimer)return;const refreshIfDue=()=>{if(document.visibilityState!=='visible'||Date.now()-lastPageRefreshAt<autoRefreshIntervalMS)return;refreshPageData({loading:false,resetLogs:false}).catch(error=>console.warn('quota management auto-refresh failed:',errorMessage(error)))};autoRefreshTimer=window.setInterval(refreshIfDue,autoRefreshIntervalMS);document.addEventListener('visibilitychange',refreshIfDue)}
  function enabledCPAAuthEntries(payload){return (Array.isArray(payload?.files)?payload.files:[]).filter(file=>{const status=value(file?.status).toLowerCase();return value(file?.id||file?.name)&&!file?.disabled&&status!=='disabled'})}
  // Query the runtime registry for every configured, enabled CPA auth. Static
  // model definitions describe every model CPA knows, not what this instance supports.
  async function syncCPAModels(){const authPayload=await host('/auth-files'),auths=enabledCPAAuthEntries(authPayload);if(!auths.length)throw new Error(uiText('CPA 当前没有已启用账号，无法同步支持的模型。','CPA has no enabled accounts to synchronize supported models from.'));const results=await Promise.allSettled(auths.map(auth=>host('/auth-files/models?name='+encodeURIComponent(value(auth.id||auth.name))))),failed=results.filter(result=>result.status==='rejected').length;if(failed)throw new Error(uiText('有 '+failed+' 个 CPA 账号的模型读取失败，未覆盖现有模型目录，请稍后重试。',failed+' CPA account model catalogs failed to load. The existing catalog was kept; retry later.'));const seen=new Map;results.forEach((result,index)=>{const auth=auths[index];(result.value?.models||[]).forEach(model=>{const id=value(model.id||model.name);if(id&&!seen.has(id))seen.set(id,{id,display_name:value(model.display_name||model.displayName||id),owner:value(model.owned_by||model.owner||model.type||auth.provider||auth.type)})})});if(!seen.size)throw new Error(uiText('CPA 当前账号未返回支持的模型。','CPA accounts returned no supported models.'));const models=Array.from(seen.values());await api('/models',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({models})});state.models=models.map(model=>({...model,available:true,synced_at:new Date().toISOString()}));return models.length}
  async function syncCPA(){const button=$('sync');if(button)button.disabled=true;try{const count=await syncCPAModels();await loadModels();await loadRates();state.modelSyncError='';render();say(uiText('已同步当前 CPA 账号支持的 '+count+' 个模型。','Synchronized '+count+' models supported by the current CPA accounts.'),true)}catch(error){state.modelSyncError=errorMessage(error);renderSyncStatus();say(state.modelSyncError)}finally{if(button)button.disabled=false}}

  function policyModelEntries(policy){const selected=new Set(policy?.allowed_models||[]),entries=new Map;state.models.forEach(model=>{const id=value(model.id);if(id)entries.set(id,{id,display:value(model.display_name||model.id)})});selected.forEach(id=>{if(!entries.has(id))entries.set(id,{id,display:id})});return Array.from(entries.values()).sort((a,b)=>a.display.localeCompare(b.display))}
  function renderPolicyModels(){const dialog=$('policy-dialog'),selected=dialog.__allowedModels||new Set,query=value($('allowed-models-search')?.value).toLowerCase(),entries=policyModelEntries({allowed_models:Array.from(selected)}).filter(model=>!query||(model.id+' '+model.display).toLowerCase().includes(query));$('allowed-models-summary').textContent=selected.size?uiText('仅允许 ','Allow only ')+number(selected.size)+uiText(' 个模型',' models'):uiText('未限制（全部模型）','Unrestricted (all models)');$('allowed-models-list').innerHTML=entries.length?entries.map(model=>'<label class="policy-model-item"><input type="checkbox" data-allowed-model="'+escapeHTML(model.id)+'" '+(selected.has(model.id)?'checked':'')+'><span><strong>'+escapeHTML(model.display)+'</strong><small>'+escapeHTML(model.id)+'</small></span></label>').join(''):'<div class="empty">'+uiText('暂无模型目录，请先同步 CPA 模型。','No model catalog yet. Synchronize CPA models first.')+'</div>'}
  const weekdayLabels=()=>uiText(['周一','周二','周三','周四','周五','周六','周日'],['Mon','Tue','Wed','Thu','Fri','Sat','Sun']);
  function accessRuleCard(rule={}){const card=document.createElement('div'),selected=new Set(rule.weekdays||[1,2,3,4,5,6,7]);card.className='access-rule';card.dataset.accessRule='';card.innerHTML='<div class="access-rule-head"><strong>'+uiText('访问时段','Access time slot')+'</strong><button type="button" class="access-rule-remove"><svg class="cc-icon"><use href="#cc-icon-trash"></use></svg>'+uiText('移除','Remove')+'</button></div><div class="form-grid"><label>'+uiText('开始时间','Start time')+'<input class="access-start" type="time" value="'+escapeHTML(rule.start||'08:00')+'"></label><label>'+uiText('结束时间','End time')+'<input class="access-end" type="time" value="'+escapeHTML(rule.end||'18:00')+'"></label></div><div class="access-weekdays">'+weekdayLabels().map((day,index)=>'<label><input type="checkbox" value="'+(index+1)+'" '+(selected.has(index+1)?'checked':'')+'>'+day+'</label>').join('')+'</div><small>'+uiText('开始时间晚于结束时间时，此时段跨午夜。','A start later than the end continues past midnight.')+'</small>';card.querySelector('.access-rule-remove').onclick=()=>{card.remove();if(!$('access-rule-list').children.length){$('access-limited').checked=false;setAccessLimited(false)}};return card}
  function addAccessRule(rule={}){const list=$('access-rule-list');if(list.children.length>=16){say(uiText('一个 Key 最多配置 16 个访问时段。','A Key supports at most 16 access time slots.'));return}list.append(accessRuleCard(rule))}
  function setAccessLimited(enabled){$('access-rule-wrap').hidden=!enabled;if(enabled&&!$('access-rule-list').children.length)addAccessRule()}
  function fillAccessPolicy(policy){const rules=policy?.access_rules||[];$('access-limited').checked=rules.length>0;$('access-timezone').value=policy?.access_timezone||'Asia/Shanghai';$('access-rule-list').replaceChildren();rules.forEach(addAccessRule);setAccessLimited(rules.length>0)}
  function readAccessPolicy(){if(!$('access-limited').checked)return {access_rules:[],access_timezone:''};const accessRules=Array.from(document.querySelectorAll('#access-rule-list [data-access-rule]')).map(card=>({weekdays:Array.from(card.querySelectorAll('.access-weekdays input:checked')).map(input=>Number(input.value)),start:value(card.querySelector('.access-start').value),end:value(card.querySelector('.access-end').value)})),accessTimezone=value($('access-timezone').value);if(!accessRules.length||accessRules.some(rule=>!rule.weekdays.length))throw new Error(uiText('每个访问时段至少选择一个星期。','Select at least one weekday for every access time slot.'));if(accessRules.some(rule=>!rule.start||!rule.end||rule.start===rule.end))throw new Error(uiText('每个访问时段必须设置不同的开始和结束时间。','Every access time slot needs different start and end times.'));if(!accessTimezone)throw new Error(uiText('请填写 IANA 时区，例如 Asia/Shanghai。','Enter an IANA time zone, for example Asia/Shanghai.'));return {access_rules:accessRules,access_timezone:accessTimezone}}
  function openPolicy(policy){state.editing=policy||null;const dialog=$('policy-dialog');dialog.__allowedModels=new Set(policy?.allowed_models||[]);$('source').replaceChildren();state.rawKeys.forEach((key,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent='CPA Key '+(index+1)+' · ••••'+String(key).slice(-4);$('source').append(option)});if(!state.rawKeys.length){const option=document.createElement('option');option.value='';option.textContent=uiText('CPA 未配置 API Key','CPA has no configured API Key');$('source').append(option)}$('source').disabled=Boolean(policy);$('name').value=policy?.name||'';$('enabled').value=policy?.enabled?'true':'false';$('five-hour-budget').value=Number(policy?.five_hour_budget_usd)>0?String(policy.five_hour_budget_usd):'';$('seven-day-budget').value=Number(policy?.seven_day_budget_usd)>0?String(policy.seven_day_budget_usd):'';$('allowed-models-search').value='';renderPolicyModels();fillAccessPolicy(policy);dialog.showModal()}
  async function savePolicy(){const name=value($('name').value);if(!name){say(uiText('请输入 Key 备注名称。','Enter a Key name.'));return}const parseBudget=id=>{const n=Number($(id).value);return Number.isFinite(n)&&n>0?n:0};const raw=state.editing?null:state.rawKeys[Number($('source').value)];if(!state.editing&&!raw){say(uiText('请先在 CPA 配置并选择 API Key。','Configure and select an API Key in CPA first.'));return}let access;try{access=readAccessPolicy()}catch(error){say(error.message);return}const policy={id:state.editing?.id||'key-'+(crypto.randomUUID?.()||Date.now().toString(36)),name,enabled:$('enabled').value==='true',allowed_models:Array.from($('policy-dialog').__allowedModels||[]),five_hour_budget_usd:parseBudget('five-hour-budget'),seven_day_budget_usd:parseBudget('seven-day-budget'),...access};try{await api('/keys',{method:state.editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({policy,api_key:raw})});closeDialog('policy-dialog');await loadSummary();say(uiText('额度设置已保存。','Quota settings saved.'),true)}catch(error){say(error.message)}}
  async function deletePolicy(id){if(!confirm(uiText('从用量管理中移除此 Key？','Remove this Key from usage management?')))return;try{await api('/keys?key_id='+encodeURIComponent(id),{method:'DELETE'});await loadSummary();say(uiText('Key 已移除。','Key removed.'),true)}catch(error){say(error.message)}}
  async function resetPolicy(id){if(!confirm(uiText('重置此 Key 的已用额度？日志会保留。','Reset this Key’s used quota? Logs are kept.')))return;try{await api('/keys/reset?key_id='+encodeURIComponent(id),{method:'POST'});await loadSummary();say(uiText('该 Key 的用量已重置。','This Key’s usage was reset.'),true)}catch(error){say(error.message)}}
  let rateEntries=new Map;
  function filterRateRows(){const query=value($('rate-card-search')?.value).toLowerCase(),status=value($('rate-card-status-filter')?.value),rows=Array.from(document.querySelectorAll('#rate-card-rows .rate-card-row'));let visible=0;rows.forEach(row=>{const matchesQuery=!query||value(row.dataset.rateSearch).includes(query),matchesStatus=!status||row.dataset.rateStatus===status;row.hidden=!(matchesQuery&&matchesStatus);if(!row.hidden)visible++});$('rate-card-filter-empty').hidden=visible>0||rows.length===0}
  function updateRateRowStatus(row){if(!row)return;const configured=Array.from(row.querySelectorAll('input[data-rate]')).some(input=>value(input.value)!=='');row.dataset.rateStatus=configured?'configured':'missing';const status=row.querySelector('.rate-status');if(status){status.className='rate-status '+(configured?'configured':'missing');status.textContent=configured?uiText('已配置','Configured'):uiText('未配置','Missing')}}
  function renderRateRows(){const models=new Map;state.models.forEach(model=>models.set(value(model.id),{model:value(model.id),display_name:value(model.display_name||model.id)}));state.rates.forEach(rate=>{if(!models.has(rate.model))models.set(rate.model,{model:rate.model,display_name:rate.model})});$('rate-card-rows').innerHTML=Array.from(models.values()).sort((a,b)=>a.display_name.localeCompare(b.display_name)).map(model=>{const rate=rateEntries.get(model.model)||{},configured=rateEntries.has(model.model),inputPlaceholder=uiText('输入','Input'),cachedPlaceholder=uiText('缓存','Cached'),outputPlaceholder=uiText('输出','Output'),inputLabel=model.display_name+' · '+inputPlaceholder,cachedLabel=model.display_name+' · '+cachedPlaceholder,outputLabel=model.display_name+' · '+outputPlaceholder,searchText=(model.model+' '+model.display_name).toLowerCase();return '<div class="rate-card-row" data-rate-model="'+encodeURIComponent(model.model)+'" data-rate-search="'+escapeHTML(searchText)+'" data-rate-status="'+(configured?'configured':'missing')+'"><strong title="'+escapeHTML(model.model)+'">'+escapeHTML(model.display_name)+'</strong><input data-rate="input" type="number" min="0" step="0.000001" value="'+(configured?Number(rate.input_usd_per_million||0):'')+'" placeholder="'+inputPlaceholder+'" aria-label="'+escapeHTML(inputLabel)+'"><input data-rate="cached" type="number" min="0" step="0.000001" value="'+(configured?Number(rate.cached_usd_per_million||0):'')+'" placeholder="'+cachedPlaceholder+'" aria-label="'+escapeHTML(cachedLabel)+'"><input data-rate="output" type="number" min="0" step="0.000001" value="'+(configured?Number(rate.output_usd_per_million||0):'')+'" placeholder="'+outputPlaceholder+'" aria-label="'+escapeHTML(outputLabel)+'"><span class="rate-status '+(configured?'configured':'missing')+'">'+(configured?uiText('已配置','Configured'):uiText('未配置','Missing'))+'</span></div>'}).join('')||'<div class="empty">'+uiText('尚未同步模型目录。','No synchronized model catalog yet.')+'</div>';filterRateRows()}
  async function openRates(){await Promise.all([loadModels(),loadRates()]);rateEntries=new Map(state.rates.map(rate=>[value(rate.model),rate]));$('rate-card-search').value='';$('rate-card-status-filter').value='';renderRateRows();$('rate-card-dialog').showModal()}
  async function saveRates(){const rates=[];document.querySelectorAll('.rate-card-row').forEach(row=>{const model=decodeURIComponent(row.dataset.rateModel||'');if(!model)return;const read=name=>{const n=Number(row.querySelector('[data-rate="'+name+'"]').value);return Number.isFinite(n)&&n>=0?n:0};const inputs=Array.from(row.querySelectorAll('input'));const configured=inputs.some(input=>value(input.value)!=='');if(configured)rates.push({model,input_usd_per_million:read('input'),cached_usd_per_million:read('cached'),output_usd_per_million:read('output')})});try{const payload=await api('/rates',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({rates})});state.rates=payload.rates||[];rateEntries=new Map(state.rates.map(rate=>[value(rate.model),rate]));closeDialog('rate-card-dialog');render();say(uiText('模型费率已保存。','Model rates saved.'),true)}catch(error){say(error.message)}}
  function addRateModel(){const model=value($('rate-card-model').value);if(!model)return;if(!state.models.some(item=>item.id===model))state.models.push({id:model,display_name:model,available:true});if(!rateEntries.has(model))rateEntries.set(model,{model,input_usd_per_million:0,cached_usd_per_million:0,output_usd_per_million:0});$('rate-card-model').value='';$('rate-card-search').value='';$('rate-card-status-filter').value='';renderRateRows()}

  function activateTab(tab){const valid=['decision','operation','forbidden'];if(!valid.includes(tab))tab='decision';const logSection=document.querySelector('.logs');if(logSection)logSection.dataset.logTab=tab;for(const name of valid){const selected=name===tab;document.querySelectorAll('[data-log-tab="'+name+'"]').forEach(button=>{button.classList.toggle('active',selected);button.setAttribute('aria-selected',selected?'true':'false')});const view=$(name+'-log-view'),tools=$(name+'-log-tools');if(view)view.hidden=!selected;if(tools)tools.hidden=!selected}document.dispatchEvent(new CustomEvent('codex-carpool:log-tab-changed',{detail:{tab}}));if(tab==='operation')loadOperationalLogs().catch(error=>say(errorMessage(error)));if(tab==='forbidden')loadForbiddenLogs().catch(error=>say(errorMessage(error)))}
  async function clearDecisionLogs(){if(!confirm(uiText('清除全部使用日志？用量统计会保留。','Clear all usage logs? Usage analytics are retained.')))return;try{await api('/logs',{method:'DELETE'});state.selectedLogs=[];await Promise.all([loadDecisionLogs(true),loadKeySparklines()]);renderAnalysisLogs();say(uiText('全部使用日志已清除，用量统计已保留。','All usage logs were cleared. Usage analytics were retained.'),true)}catch(error){say(error.message)}}
  async function clearOperationalLogs(){if(!confirm(uiText('清除全部插件运行日志？','Clear all plugin runtime logs?')))return;try{await api('/operation-logs',{method:'DELETE'});await loadOperationalLogs(true);say(uiText('全部运行日志已清除。','All runtime logs were cleared.'),true)}catch(error){say(error.message)}}
  function openLogDetail(log){if(!log)return;const set=(id,v)=>{$(id).textContent=v===undefined||v===null||v===''?'—':String(v)};set('log-detail-time',formatLogTime(log.requested_at));set('log-detail-key-name',keyFor(log.key_id)?.name);set('log-detail-model',log.model);set('log-detail-decision',decisionText(log));set('log-detail-token',tokens(log.input_tokens)+' / '+tokens(log.cached_tokens)+' / '+tokens(log.output_tokens));set('log-detail-cost',amountUSD((Number(log.cost_micros)||0)/1000000));set('log-detail-http',log.status_code);set('log-detail-account',log.auth_id);set('log-detail-request',log.request_content);set('log-detail-description',log.reason);$('log-detail-dialog').showModal()}
  function openKeyLogs(keyID){state.keyLogKeyID=value(keyID);state.keyLogs=[];state.keyLogPage={page:1,page_size:10,total:0,total_pages:0};$('key-log-from').value='';$('key-log-to').value='';$('key-log-search').value='';$('key-log-search').dispatchEvent(new Event('input',{bubbles:true}));renderKeyLogs();$('key-log-dialog').showModal();withLoading(loadingTargets.keyLog,()=>loadKeyLogs(true)).catch(error=>say(errorMessage(error)))}

  // Clear controls are static HTML so CPA host mutations cannot remove the search affordance.
  function wireSearchClears(){document.querySelectorAll('[data-clear-search]').forEach(clear=>{const input=$(clear.dataset.clearSearch);if(!input)return;const sync=()=>{clear.hidden=!value(input.value)};const run=()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));const query=$(clear.dataset.clearQuery);if(query)query.click();input.focus();sync()};clear.onclick=event=>{event.preventDefault();event.stopPropagation();run()};clear.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();run()}};input.addEventListener('input',sync);sync()})}
  function wire(){
    $('dialog-title').textContent=uiText('额度设置','Quota settings');
    $('log-tab-description').textContent=uiText('查看请求结果、Token 明细、消耗（USD）和插件运行状态','View request outcomes, Token details, spend (USD), and plugin status');
    $('refresh').onclick=()=>refreshPageData({loading:true,resetLogs:true}).catch(error=>say(errorMessage(error)));
    $('sync').onclick=syncCPA;$('manage').onclick=()=>withLoading(loadingTargets.catalog,async()=>{await loadKeys();openPolicy(null)}).catch(error=>say(errorMessage(error)));$('quota-debug-open').onclick=()=>openRates().catch(error=>say(errorMessage(error)));$('search').oninput=renderKeys;$('key-status-filter').onchange=renderKeys;$('key-detail-close').onclick=closeKeyDetail;$('key-detail-backdrop').onclick=closeKeyDetail;$('risk-list').onclick=event=>{if(event.target.closest('[data-risk-action="rates"]'))openRates().catch(error=>say(errorMessage(error)))};
    $('close').onclick=()=>closeDialog('policy-dialog');$('cancel').onclick=()=>closeDialog('policy-dialog');$('save').onclick=savePolicy;
    $('allowed-models-search').oninput=renderPolicyModels;$('allowed-models-list').onchange=event=>{const input=event.target.closest('[data-allowed-model]');if(!input)return;const set=$('policy-dialog').__allowedModels||new Set;$('policy-dialog').__allowedModels=set;if(input.checked)set.add(input.dataset.allowedModel);else set.delete(input.dataset.allowedModel);renderPolicyModels()};$('allowed-models-all').onclick=()=>{$('policy-dialog').__allowedModels=new Set(state.models.map(model=>value(model.id)).filter(Boolean));renderPolicyModels()};$('allowed-models-clear').onclick=()=>{$('policy-dialog').__allowedModels=new Set;renderPolicyModels()};$('access-limited').onchange=()=>setAccessLimited($('access-limited').checked);$('access-rule-add').onclick=()=>addAccessRule();
    $('rate-card-close').onclick=()=>closeDialog('rate-card-dialog');$('rate-card-cancel').onclick=()=>closeDialog('rate-card-dialog');$('rate-card-save').onclick=saveRates;$('rate-card-add-button').onclick=addRateModel;$('rate-card-search').oninput=filterRateRows;$('rate-card-status-filter').onchange=filterRateRows;$('rate-card-rows').oninput=event=>{const row=event.target.closest('.rate-card-row');updateRateRowStatus(row);filterRateRows()};$('key-detail-edit').onclick=()=>{const key=keyFor(state.selected);if(key)openPolicy(key)};$('key-detail-reset').onclick=()=>{const key=keyFor(state.selected);if(key)resetPolicy(key.id)};$('key-detail-unmanage').onclick=()=>{const key=keyFor(state.selected);if(key)deletePolicy(key.id)};
    $('analysis-preset').onchange=()=>{const today=new Date(),from=new Date(today);const preset=$('analysis-preset').value;if(preset==='seven')from.setDate(today.getDate()-6);if(preset==='month')from.setDate(1);if(preset==='year')from.setMonth(0,1);$('analysis-from').value=localDateISO(from);$('analysis-to').value=localDateISO(today);if(preset!=='custom')$('analysis-granularity').value=preset==='today'?'hour':(preset==='year'?'month':'day')};$('analysis-apply').onclick=()=>loadSelected().catch(error=>say(error.message));
    const logSection=document.querySelector('.logs');if(logSection)logSection.dataset.logTab='decision';document.querySelectorAll('[data-log-tab]').forEach(button=>button.addEventListener('click',()=>activateTab(button.dataset.logTab)));
    const wireLogQuery=(name,loader)=>{const query=$(name+'-query'),search=$(name+'-search');query.onclick=()=>loader(true).catch(error=>say(errorMessage(error)));search.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();query.click()}}};wireLogQuery('decision',loadDecisionLogs);wireLogQuery('operation',loadOperationalLogs);wireLogQuery('forbidden',loadForbiddenLogs);wireLogQuery('key-log',loadKeyLogs);wireSearchClears();$('key-log-filter-clear').onclick=()=>{for(const id of ['key-log-from','key-log-to','key-log-search'])$(id).value='';$('key-log-search').dispatchEvent(new Event('input',{bubbles:true}));$('key-log-query').click()};$('decision-filter').onchange=()=>loadDecisionLogs(true).catch(error=>say(errorMessage(error)));
    $('decision-refresh').onclick=()=>loadDecisionLogs(false).catch(error=>say(errorMessage(error)));$('decision-clear').onclick=clearDecisionLogs;$('operation-refresh').onclick=()=>loadOperationalLogs(false).catch(error=>say(errorMessage(error)));$('operation-clear').onclick=clearOperationalLogs;$('forbidden-refresh').onclick=()=>loadForbiddenLogs(false).catch(error=>say(errorMessage(error)));$('forbidden-clear').onclick=async()=>{if(!confirm(uiText('清除全部内容拦截日志？','Clear all content-blocking logs?')))return;try{await api('/forbidden-logs',{method:'DELETE'});await Promise.all([loadForbiddenLogs(true),loadSelectedLogs()]);renderAnalysisLogs();say(uiText('全部内容拦截日志已清除。','All content-blocking logs were cleared.'),true)}catch(error){say(errorMessage(error))}};
    $('logs').onclick=event=>{const button=event.target.closest('.log-detail-open');if(button)openLogDetail(state.logs[Number(button.dataset.logIndex)])};$('key-logs').onclick=event=>{const button=event.target.closest('.key-log-detail');if(button)openLogDetail(state.keyLogs[Number(button.dataset.keyLogIndex)])};$('forbidden-logs').onclick=event=>{const button=event.target.closest('.forbidden-log-detail');if(button)openLogDetail(state.forbiddenLogs[Number(button.dataset.logIndex)])};$('decision-prev').onclick=()=>{if(state.decisionPage.page>1){state.decisionPage.page--;loadDecisionLogs(false).catch(error=>say(error.message))}};$('decision-next').onclick=()=>{if(state.decisionPage.page<state.decisionPage.total_pages){state.decisionPage.page++;loadDecisionLogs(false).catch(error=>say(error.message))}};$('key-log-prev').onclick=()=>{if(state.keyLogPage.page>1){state.keyLogPage.page--;loadKeyLogs(false).catch(error=>say(errorMessage(error)))}};$('key-log-next').onclick=()=>{if(state.keyLogPage.page<state.keyLogPage.total_pages){state.keyLogPage.page++;loadKeyLogs(false).catch(error=>say(errorMessage(error)))}};$('key-log-close').onclick=()=>closeDialog('key-log-dialog');$('operation-prev').onclick=()=>{if(state.operationPage.page>1){state.operationPage.page--;loadOperationalLogs().catch(error=>say(error.message))}};$('operation-next').onclick=()=>{if(state.operationPage.page<state.operationPage.total_pages){state.operationPage.page++;loadOperationalLogs().catch(error=>say(error.message))}};$('forbidden-prev').onclick=()=>{if(state.forbiddenPage.page>1){state.forbiddenPage.page--;loadForbiddenLogs().catch(error=>say(error.message))}};$('forbidden-next').onclick=()=>{if(state.forbiddenPage.page<state.forbiddenPage.total_pages){state.forbiddenPage.page++;loadForbiddenLogs().catch(error=>say(error.message))}};$('log-detail-close').onclick=()=>closeDialog('log-detail-dialog');$('log-detail-close-footer').onclick=()=>closeDialog('log-detail-dialog');
    window.__ccPanelBridge?.attach?.({state,render,renderLogs,renderOperationalLogs,cpaLocale,uiText,tokens,showToast,say});
  }
  async function boot(){wire();$('analysis-preset').onchange();try{await refreshPageData({loading:true,resetLogs:true})}catch(error){say(errorMessage(error))}render();startAutoRefresh()}
  // Content filtering is isolated from dollar metering; built-ins can be disabled but only custom RE2 expressions can be deleted.
  function wireContentFilter(){
    const dialog=$('content-filter-dialog');if(!dialog)return;
    const renderTerms=()=>{
      const terms=dialog.__settings?.terms||[],query=value($('content-filter-search').value).toLowerCase(),visible=terms.map((term,index)=>({term,index})).filter(item=>!query||String(item.term.value||'').toLowerCase().includes(query)||String(item.term.category||'').toLowerCase().includes(query));
      $('content-filter-count').textContent=number(visible.length)+' / '+number(terms.length);
      $('content-filter-terms').innerHTML=visible.map(item=>{
        const builtin=item.term.source==='builtin',source=uiText(builtin?'内置':'自定义',builtin?'Built-in':'Custom'),operation=builtin?'<span class="content-filter-fixed">'+uiText('内置','Built-in')+'</span>':'<button type="button" data-remove-term="'+item.index+'"><svg class="cc-icon"><use href="#cc-icon-trash"></use></svg>'+uiText('删除','Delete')+'</button>';
        return '<div class="content-filter-term"><label class="content-filter-term-switch" title="'+escapeHTML(uiText('启用表达式','Enable expression'))+'"><input type="checkbox" role="switch" aria-label="'+escapeHTML(uiText('启用表达式 ','Enable expression ')+String(item.term.value||''))+'" '+(item.term.enabled?'checked':'')+' data-term-index="'+item.index+'"><span class="content-filter-switch" aria-hidden="true"><i></i></span></label><code title="'+escapeHTML(item.term.value)+'">'+escapeHTML(item.term.value)+'</code><span class="content-filter-tag">'+escapeHTML(item.term.category||'custom')+'</span><span class="content-filter-tag source">'+source+'</span>'+operation+'</div>';
      }).join('')||'<div class="empty">'+uiText('没有匹配的表达式。','No matching expressions.')+'</div>';
    };
    $('content-filter-open')?.addEventListener('click',async()=>{try{dialog.__settings=(await api('/content-filter')).settings||{enabled:true,terms:[]};$('content-filter-enabled').checked=Boolean(dialog.__settings.enabled);renderTerms();dialog.showModal()}catch(error){say(errorMessage(error))}});
    $('content-filter-close').onclick=()=>closeDialog('content-filter-dialog');$('content-filter-cancel').onclick=()=>closeDialog('content-filter-dialog');$('content-filter-search').oninput=renderTerms;
    $('content-filter-add').onclick=()=>{const expression=value($('content-filter-value').value);if(!expression)return;(dialog.__settings.terms||[]).push({value:expression,category:value($('content-filter-category').value)||'custom',source:'custom',enabled:true});$('content-filter-value').value='';$('content-filter-category').value='';renderTerms()};
    $('content-filter-save').onclick=async()=>{dialog.__settings.enabled=$('content-filter-enabled').checked;try{await api('/content-filter',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings:dialog.__settings})});closeDialog('content-filter-dialog');say(uiText('内容正则设置已保存。','Content-regex settings saved.'),true)}catch(error){say(errorMessage(error))}};
    $('content-filter-terms').onchange=event=>{const input=event.target.closest('[data-term-index]');if(input&&dialog.__settings?.terms?.[Number(input.dataset.termIndex)])dialog.__settings.terms[Number(input.dataset.termIndex)].enabled=input.checked};
    $('content-filter-terms').onclick=event=>{const remove=event.target.closest('[data-remove-term]');if(remove){dialog.__settings.terms.splice(Number(remove.dataset.removeTerm),1);renderTerms()}};
  }
  wireContentFilter();
  boot().catch(error=>say(errorMessage(error)));
})();
