(()=>{
  const locale=()=>{let value='';try{const root=window.parent.document.documentElement;value=String(root.lang||root.dataset.locale||root.dataset.language||'')}catch{}return /^zh/i.test(value||navigator.language||'zh-CN')?'zh-CN':'en-US'};
  const text=(zh,en)=>locale().startsWith('zh')?zh:en;
  const staticPairs=[
    ['正在连接用量管理','Connecting to usage management'],['插件管理  /  用量管理','Plugin management / usage management'],
    ['同步 CPA 模型','Sync CPA models'],['内容正则拦截','Content regex'],['费率设置','Rate settings'],['刷新','Refresh'],
    ['用量管理','Usage management'],['列表展示额度使用率和今日用量趋势；点击“管理”查看详细分析','The list shows quota usage and today’s usage trend. Select Manage for detailed analysis.'],['搜索 Key','Search Keys'],['搜索 Key 备注或尾号','Search Key name or suffix'],['Key 状态筛选','Key status filter'],
    ['状态：全部','Status: All'],['额度限制','Budget enforced'],['仅统计','Track only'],['新增 Key','Add Key'],['已添加 Key','Added Keys'],['今日模型用量排行','Today model usage ranking'],['全部 Key · 今日','All Keys · Today'],
    ['5 小时','5-hour'],['7 天','7-day'],['今日趋势','Today trend'],['状态','Status'],['操作','Actions'],
    ['当前 Key · 用量分析','Current Key · Usage analysis'],['请选择 Key','Select a Key'],['仅统计经过 CPA 的已完成请求，外部绕过不分摊到 Key','Only completed requests through CPA are counted; bypass traffic is never assigned to a Key.'],
    ['关闭','Close'],['关闭分析','Close analysis'],['编辑额度','Edit quota'],['重置用量','Reset usage'],['移除 Key','Remove Key'],
    ['时间与维度筛选','Time and dimension'],['管理面板内可切换趋势时间','Change the trend range in the management panel'],['今日','Today'],['近 7 天','Last 7 days'],['本月','This month'],['本年','This year'],['自定义','Custom'],['至','to'],['按小时','Hourly'],['按日','Daily'],['按月','Monthly'],['按年','Yearly'],['查询','Query'],
    ['预算窗口','Budget windows'],['百分比','Percentage'],['成本占比','Cost share'],['按费率','By rate'],['Token 趋势','Token trend'],['折线 / 面积图，不使用柱状图','Line / area chart, not bars'],['窗口开始','Window start'],
    ['Token 拆分','Token breakdown'],['输入 / 缓存 / 输出','Input / cached / output'],['模型消耗排行','Model spend ranking'],['Top 模型','Top models'],['7 天活跃热力','7-day activity heatmap'],['请求活跃度','Request activity'],['最近日志摘要','Recent log summary'],['可查看完整日志','Full logs remain available'],['诊断与风险','Diagnostics and risks'],['费率 / 预算 / 拦截','Rates / budgets / blocking'],
    ['日志与诊断','Logs and diagnostics'],['查看请求结果、Token 明细、消耗（USD）和插件运行状态','View request outcomes, Token details, spend (USD), and plugin status'],['使用日志','Usage logs'],['内容拦截日志','Content-blocking logs'],['运行日志','Runtime logs'],['全部决策','All decisions'],['已完成','Completed'],['已拦截','Blocked'],['失败','Failed'],['清除日志','Clear logs'],['清除搜索','Clear search'],['搜索使用日志','Search usage logs'],['搜索模型、原因或账号','Search model, reason, or account'],['决策状态','Decision status'],['搜索运行日志','Search runtime logs'],['搜索事件或说明','Search event or description'],['搜索内容拦截日志','Search content-blocking logs'],['搜索表达式或模型','Search expression or model'],
    ['时间','Time'],['Key','Key'],['模型','Model'],['请求内容','Request content'],['决策','Decision'],['输入 Token','Input Tokens'],['缓存 Token','Cached Tokens'],['输出 Token','Output Tokens'],['消耗（USD）','Spend (USD)'],['账号','Account'],['说明','Description'],['操作','Actions'],['级别','Level'],['事件','Event'],['命中表达式','Matched expression'],['分类','Category'],['上一页','Previous'],['下一页','Next'],
    ['额度设置','Quota settings'],['Key 备注名称','Key name'],['例如：开发组 Key','For example: Development Key'],['启用额度限制','Enable quota enforcement'],['仅统计（超额不限制）','Track only (do not block overages)'],['5 小时额度（USD）','5-hour budget (USD)'],['7 天额度（USD）','7-day budget (USD)'],['留空或 0 = 不限','Empty or 0 = unlimited'],['允许模型','Allowed models'],['未限制（全部模型）','Unrestricted (all models)'],['全选目录模型','Select all catalog models'],['不限制','Unrestricted'],['搜索模型 ID 或名称','Search model ID or name'],['不勾选任何模型表示此 Key 可使用全部模型；勾选后只允许使用所选模型。','No selection allows every model. After selection, only checked models are allowed.'],
    ['Key 添加后始终统计 Token、消耗（USD）、5 小时与 7 天窗口及日志；选择“仅统计”时超额请求继续放行。外部绕过不会归集到此 Key。模型必须在费率设置中存在，三项费率都填 0 表示免费。','Added Keys always track Tokens, spend (USD), 5-hour and 7-day windows, and logs. Track-only Keys continue when over quota. External bypass traffic is not assigned to a Key. Models require a configured rate; all-zero rates are free.'],
    ['允许访问时段','Allowed access times'],['不启用表示不限时访问','Disabled means access at any time'],['仅允许指定时段','Only during specified times'],['时区','Time zone'],['例如 Asia/Shanghai','For example Asia/Shanghai'],['添加时段','Add time slot'],['额度只限制此 Key 经过 CPA 的请求；不经过 CPA 的外部使用不会归集到此 Key。模型必须在费率设置中存在，三项费率都填 0 表示免费。','Budgets apply only to this Key’s requests through CPA. External bypass traffic is not assigned to it. Models need a rate card; all three rates at zero means free.'],['取消','Cancel'],['保存','Save'],
    ['模型费率设置','Model rate settings'],['单位：USD / 百万 Token。模型来自 CPA 当前支持目录；输入、缓存输入、输出分别计价。费率全部为 0 即免费，未配置费率的模型会被暂停调用。','Unit: USD per million Tokens. Models come from the current CPA catalog. Input, cached input, and output are priced separately. All-zero rates are free; models without a rate are blocked.'],['费率配置状态','Rate configuration status'],['已配置','Configured'],['未配置','Missing'],['没有匹配的模型。','No matching models.'],['输入','Input'],['缓存','Cached'],['输出','Output'],['添加模型 ID','Add model ID'],['添加','Add'],['保存费率','Save rates'],
    ['Key 请求日志','Key request logs'],['仅显示当前 Key 的请求记录','Only requests for the current Key'],['日志详情','Log details'],['来源','Source'],['内容正则拦截','Content regex'],['开启内容正则拦截','Enable content-regex blocking'],['使用安全的 RE2 正则表达式，不区分大小写；命中后在路由前返回 403。','Use safe, case-insensitive RE2 expressions. Return 403 before routing when matched.'],['表达式列表','Expression list'],['正则表达式','Regular expression'],['搜索表达式或分类','Search expression or category'],['添加 RE2 正则表达式','Add RE2 expression'],['请组合“危险目标 + 行为意图”，避免使用 .* 等可匹配空内容或过宽的表达式。','Combine a dangerous target with harmful intent. Avoid .* and other empty or overly broad expressions.'],['内置','Built-in'],['自定义','Custom'],['保存','Save']
  ];
  const zhToEn=new Map(staticPairs),enToZh=new Map(staticPairs.map(pair=>[pair[1],pair[0]]));
  const translateExact=value=>{const raw=String(value??''),trimmed=raw.trim(),dictionary=locale().startsWith('zh')?enToZh:zhToEn,translated=dictionary.get(trimmed);return translated===undefined?raw:raw.replace(trimmed,translated)};
  const localizeStatic=()=>{document.title=text('用量管理','Usage management');const root=document.querySelector('.cc-panel');if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:node=>node.parentElement?.closest('script,style,svg')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});for(let node=walker.nextNode();node;node=walker.nextNode())node.nodeValue=translateExact(node.nodeValue);root.querySelectorAll('[placeholder],[aria-label],[title]').forEach(node=>{for(const attribute of ['placeholder','aria-label','title'])if(node.hasAttribute(attribute))node.setAttribute(attribute,translateExact(node.getAttribute(attribute)))})};
  const toast=(message,ok=true)=>{if(!message)return;let region=document.getElementById('toast-region');if(!region){region=document.createElement('div');region.id='toast-region';region.setAttribute('aria-live','assertive');document.body.append(region)}const item=document.createElement('div');item.setAttribute('role',ok?'status':'alert');item.textContent=message;region.append(item);item.onclick=()=>item.remove();setTimeout(()=>item.remove(),ok?3600:6500)};
  window.state=window.state||{locale:''};window.render=window.render||(()=>{});window.renderLogs=window.renderLogs||(()=>{});window.renderOperationalLogs=window.renderOperationalLogs||(()=>{});window.uiText=window.uiText||text;window.tokens=window.tokens||(value=>String(Number(value)||0));window.cpaLocale=window.cpaLocale||locale;window.__ccToast=toast;
  window.__ccPanelBridge={attach(panel){if(!panel?.state)return;panel.state.locale=panel.cpaLocale().startsWith('zh')?'zh':'en';window.state=panel.state;window.render=panel.render;window.renderLogs=panel.renderLogs;window.renderOperationalLogs=panel.renderOperationalLogs;window.uiText=panel.uiText;window.tokens=panel.tokens;window.cpaLocale=panel.cpaLocale;window.showToast=panel.showToast;window.say=panel.say},afterRender(){localizeStatic();window.__ccAfterRender?.()}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',localizeStatic,{once:true});else localizeStatic();
  try{new MutationObserver(localizeStatic).observe(window.parent.document.documentElement,{attributes:true,attributeFilter:['lang','data-locale','data-language']})}catch{}
  const nativeFetch=window.fetch?.bind(window);if(nativeFetch&&!window.__ccFetchTimeoutInstalled){window.__ccFetchTimeoutInstalled=true;window.fetch=async(input,init={})=>{if(typeof AbortController==='undefined')return nativeFetch(input,init);const options=init||{},url=typeof input==='string'?input:input?.url||'',controller=new AbortController(),callerSignal=Object.prototype.hasOwnProperty.call(options,'signal')?options.signal:(typeof Request!=='undefined'&&input instanceof Request?input.signal:undefined);let timedOut=false;if(callerSignal){if(callerSignal.aborted)controller.abort(callerSignal.reason);else callerSignal.addEventListener('abort',()=>controller.abort(callerSignal.reason),{once:true})}const timer=setTimeout(()=>{timedOut=true;controller.abort()},15000);try{return await nativeFetch(input,{...options,signal:controller.signal})}catch(error){if(timedOut&&!callerSignal?.aborted)throw new Error(text('管理请求超时，请检查 CPA 连接后重试。','The management request timed out. Check the CPA connection and retry.'));throw error}finally{clearTimeout(timer)}}}
})();
